name: aquascan
description: A comprehensive water quality monitoring system with AI analysis,
  admin dashboard, and interactive mapping capabilities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9

  # State Management & Network
  provider: ^6.1.5
  http: ^1.4.0
  dio: ^5.8.0+1

  # Location Services
  geolocator: ^14.0.1
  geocoding: ^4.0.0

  # Image Handling
  image_picker: ^1.1.2
  image: ^4.5.4
  flutter_image_compress: ^2.4.0

  # File & Path Management
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.1

  # Map Dependencies
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # UI & Animation
  lottie: ^3.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1

  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1
  sqflite: ^2.4.2
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0

  # JSON
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

# Flutter Configuration
flutter:
  uses-material-design: true

# FIXED: Updated dependency overrides to resolve SchemeRainbow/SchemeFruitSalad errors
dependency_overrides:
  # Material utilities - use latest stable version
  material_color_utilities: ^0.11.1
  
  # Collection fix for compatibility
  collection: ^1.18.0
  
  # Meta package version alignment
  meta: ^1.15.0
  
  # Web compatibility for latest Flutter
  web: ^1.1.0
  
  # Dynamic color package - use compatible version
  dynamic_color: ^1.7.0